export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL'

export const FETCH_SINGLE_MESSAGE_REQUEST = 'FETCH_SINGLE_MESSAGE_REQUEST';
export const FETCH_SINGLE_MESSAGE_SUCCESS = 'FETCH_SINGLE_MESSAGE_SUCCESS';
export const FETCH_SINGLE_MESSAGE_FAIL = 'FETCH_SINGLE_MESSAGE_FAIL';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_LOADING';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';